# Generated by Django 5.1.4 on 2025-02-06 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='homepage_banners/')),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='ProductCat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('product_type', models.CharField(choices=[('Whey Protein', 'Whey Protein'), ('Mass Gainer', 'Mass Gainer'), ('Pre Workout', 'Pre Workout'), ('Peanut Butter', 'Peanut Butter'), ('Protein Bar', 'Protein Bar')], max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('flavour', models.CharField(max_length=255)),
                ('size', models.PositiveIntegerField()),
                ('size_unit', models.CharField(choices=[('kg', 'Kilogram'), ('gm', 'Gram')], default='kg', max_length=2)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('front_image', models.ImageField(upload_to='front_images/')),
                ('is_discounted', models.BooleanField(default=False)),
                ('discounted_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bestselling_rank', models.PositiveIntegerField()),
                ('stock', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('productcat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productcat', to='shop.productcat')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images/')),
                ('is_primary', models.BooleanField(default=False)),
                ('alt_text', models.CharField(blank=True, max_length=255, null=True)),
                ('image_order', models.PositiveIntegerField(default=0)),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.product', to_field='sku')),
            ],
        ),
    ]
