# Generated by Django 5.1.4 on 2025-01-16 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='product_sku',
            new_name='sku',
        ),
    ]
