# Generated by Django 5.1.4 on 2025-01-16 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_productimage_sku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='sku',
        ),
    ]
