# Generated by Django 5.1.4 on 2025-01-16 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_productimage_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='sku',
            field=models.ForeignKey(default='WHEY-CHOC-3KG', on_delete=django.db.models.deletion.CASCADE, related_name='sk', to='shop.product', to_field='sku'),
            preserve_default=False,
        ),
    ]
