# Generated by Django 5.1.4 on 2025-01-17 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_productimage_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.product', to_field='sku'),
        ),
    ]
