# Generated by Django 5.1.4 on 2025-01-17 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_productimage_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bestselling_rank',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
