# Generated by Django 5.1.4 on 2025-01-18 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_product_bestselling_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='front_image',
            field=models.ImageField(default=1, upload_to='front_images/'),
            preserve_default=False,
        ),
    ]
